-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity infer_set3DFloatArray_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    array_r_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    array_r_ce0 : OUT STD_LOGIC;
    array_r_we0 : OUT STD_LOGIC;
    array_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of infer_set3DFloatArray_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv13_1520 : STD_LOGIC_VECTOR (12 downto 0) := "1010100100000";
    constant ap_const_lv10_1A0 : STD_LOGIC_VECTOR (9 downto 0) := "0110100000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv13_1A0 : STD_LOGIC_VECTOR (12 downto 0) := "0000110100000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal indvar_flatten17_reg_74 : STD_LOGIC_VECTOR (12 downto 0);
    signal i_reg_85 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten_reg_96 : STD_LOGIC_VECTOR (9 downto 0);
    signal ii_reg_107 : STD_LOGIC_VECTOR (3 downto 0);
    signal iii_reg_118 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln8_fu_129_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln8_fu_135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_296 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_296_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_296_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_fu_141_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_reg_300 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_reg_300_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_reg_300_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal mul7_mid2_v_v_fu_153_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul7_mid2_v_v_reg_308 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln10_12_fu_171_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_179_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_reg_323 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln12_mid216_fu_205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_mid216_reg_328 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln10_fu_211_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln10_reg_333 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln10_11_fu_230_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal add_ln12_fu_242_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_condition_pp0_exit_iter2_state4 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_phi_mux_i_phi_fu_89_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln14_fu_277_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln8_4_fu_147_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln10_4_fu_165_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln12_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ii_mid27_fu_187_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln10_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln10_fu_222_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_mid1_fu_254_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln12_mid214_fu_248_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln10_10_fu_261_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_282_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln10_10_cast_fu_268_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln14_fu_272_p2 : STD_LOGIC_VECTOR (12 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln14_fu_272_p2 : signal is "no";
    signal grp_fu_282_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_282_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_282_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_282_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_282_p20 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component infer_mac_muladd_4ns_10ns_6ns_13_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;



begin
    mac_muladd_4ns_10ns_6ns_13_4_1_U44 : component infer_mac_muladd_4ns_10ns_6ns_13_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 4,
        din1_WIDTH => 10,
        din2_WIDTH => 6,
        dout_WIDTH => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_282_p0,
        din1 => grp_fu_282_p1,
        din2 => grp_fu_282_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_282_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter2_state4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter2_state4))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_reg_85_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln8_reg_296 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                i_reg_85 <= mul7_mid2_v_v_reg_308;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_85 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    ii_reg_107_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln8_reg_296_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ii_reg_107 <= select_ln10_11_fu_230_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                ii_reg_107 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    iii_reg_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln8_reg_296_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                iii_reg_118 <= add_ln12_fu_242_p2;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                iii_reg_118 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    indvar_flatten17_reg_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln8_fu_135_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten17_reg_74 <= add_ln8_fu_129_p2;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten17_reg_74 <= ap_const_lv13_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln8_fu_135_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten_reg_96 <= select_ln10_12_fu_171_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_reg_96 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln8_reg_296_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln10_reg_333 <= add_ln10_fu_211_p2;
                icmp_ln12_mid216_reg_328 <= icmp_ln12_mid216_fu_205_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln8_fu_135_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln10_reg_300 <= icmp_ln10_fu_141_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln10_reg_300_pp0_iter1_reg <= icmp_ln10_reg_300;
                icmp_ln8_reg_296 <= icmp_ln8_fu_135_p2;
                icmp_ln8_reg_296_pp0_iter1_reg <= icmp_ln8_reg_296;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln10_reg_300_pp0_iter2_reg <= icmp_ln10_reg_300_pp0_iter1_reg;
                icmp_ln8_reg_296_pp0_iter2_reg <= icmp_ln8_reg_296_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln8_fu_135_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                mul7_mid2_v_v_reg_308 <= mul7_mid2_v_v_fu_153_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln10_reg_300_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                    tmp_reg_323(8 downto 5) <= tmp_fu_179_p3(8 downto 5);
            end if;
        end if;
    end process;
    tmp_reg_323(4 downto 0) <= "00000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln10_4_fu_165_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_96) + unsigned(ap_const_lv10_1));
    add_ln10_fu_211_p2 <= std_logic_vector(unsigned(ii_mid27_fu_187_p3) + unsigned(ap_const_lv4_1));
    add_ln12_fu_242_p2 <= std_logic_vector(unsigned(select_ln10_fu_222_p3) + unsigned(ap_const_lv6_1));
    add_ln14_fu_272_p2 <= std_logic_vector(unsigned(grp_fu_282_p3) + unsigned(select_ln10_10_cast_fu_268_p1));
    add_ln8_4_fu_147_p2 <= std_logic_vector(unsigned(ap_phi_mux_i_phi_fu_89_p4) + unsigned(ap_const_lv4_1));
    add_ln8_fu_129_p2 <= std_logic_vector(unsigned(indvar_flatten17_reg_74) + unsigned(ap_const_lv13_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state6 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter2_state4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_condition_pp0_exit_iter2_state4 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter2_state4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp0_flush_enable_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln8_fu_135_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((icmp_ln8_fu_135_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_i_phi_fu_89_p4_assign_proc : process(i_reg_85, ap_CS_fsm_pp0_stage0, icmp_ln8_reg_296, mul7_mid2_v_v_reg_308, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((icmp_ln8_reg_296 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_i_phi_fu_89_p4 <= mul7_mid2_v_v_reg_308;
        else 
            ap_phi_mux_i_phi_fu_89_p4 <= i_reg_85;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    array_r_address0 <= zext_ln14_fu_277_p1(13 - 1 downto 0);

    array_r_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            array_r_ce0 <= ap_const_logic_1;
        else 
            array_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    array_r_d0 <= ap_const_lv32_0;

    array_r_we0_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln8_reg_296_pp0_iter2_reg, ap_enable_reg_pp0_iter3)
    begin
        if (((icmp_ln8_reg_296_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            array_r_we0 <= ap_const_logic_1;
        else 
            array_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_282_p0 <= grp_fu_282_p00(4 - 1 downto 0);
    grp_fu_282_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul7_mid2_v_v_fu_153_p3),13));
    grp_fu_282_p1 <= ap_const_lv13_1A0(10 - 1 downto 0);
    grp_fu_282_p2 <= grp_fu_282_p20(6 - 1 downto 0);
    grp_fu_282_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln10_fu_222_p3),13));
    icmp_ln10_fu_141_p2 <= "1" when (indvar_flatten_reg_96 = ap_const_lv10_1A0) else "0";
    icmp_ln12_fu_199_p2 <= "1" when (iii_reg_118 = ap_const_lv6_20) else "0";
    icmp_ln12_mid216_fu_205_p2 <= (not_exitcond_flatten_fu_194_p2 and icmp_ln12_fu_199_p2);
    icmp_ln8_fu_135_p2 <= "1" when (indvar_flatten17_reg_74 = ap_const_lv13_1520) else "0";
    ii_mid27_fu_187_p3 <= 
        ap_const_lv4_0 when (icmp_ln10_reg_300_pp0_iter1_reg(0) = '1') else 
        ii_reg_107;
    mul7_mid2_v_v_fu_153_p3 <= 
        add_ln8_4_fu_147_p2 when (icmp_ln10_fu_141_p2(0) = '1') else 
        ap_phi_mux_i_phi_fu_89_p4;
    not_exitcond_flatten_fu_194_p2 <= (icmp_ln10_reg_300_pp0_iter1_reg xor ap_const_lv1_1);
    or_ln10_fu_217_p2 <= (icmp_ln12_mid216_fu_205_p2 or icmp_ln10_reg_300_pp0_iter1_reg);
    p_mid1_fu_254_p3 <= (add_ln10_reg_333 & ap_const_lv5_0);
    select_ln10_10_cast_fu_268_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln10_10_fu_261_p3),13));
    select_ln10_10_fu_261_p3 <= 
        p_mid1_fu_254_p3 when (icmp_ln12_mid216_reg_328(0) = '1') else 
        zext_ln12_mid214_fu_248_p3;
    select_ln10_11_fu_230_p3 <= 
        add_ln10_fu_211_p2 when (icmp_ln12_mid216_fu_205_p2(0) = '1') else 
        ii_mid27_fu_187_p3;
    select_ln10_12_fu_171_p3 <= 
        ap_const_lv10_1 when (icmp_ln10_fu_141_p2(0) = '1') else 
        add_ln10_4_fu_165_p2;
    select_ln10_fu_222_p3 <= 
        ap_const_lv6_0 when (or_ln10_fu_217_p2(0) = '1') else 
        iii_reg_118;
    tmp_fu_179_p3 <= (ii_reg_107 & ap_const_lv5_0);
    zext_ln12_mid214_fu_248_p3 <= 
        ap_const_lv9_0 when (icmp_ln10_reg_300_pp0_iter2_reg(0) = '1') else 
        tmp_reg_323;
    zext_ln14_fu_277_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln14_fu_272_p2),64));
end behav;
