// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module infer_set3DFloatArray_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        array_r_address0,
        array_r_ce0,
        array_r_we0,
        array_r_d0,
        array1_address0,
        array1_ce0,
        array1_we0,
        array1_d0,
        array2_address0,
        array2_ce0,
        array2_we0,
        array2_d0,
        array3_address0,
        array3_ce0,
        array3_we0,
        array3_d0,
        array4_address0,
        array4_ce0,
        array4_we0,
        array4_d0,
        array5_address0,
        array5_ce0,
        array5_we0,
        array5_d0,
        array6_address0,
        array6_ce0,
        array6_we0,
        array6_d0,
        array7_address0,
        array7_ce0,
        array7_we0,
        array7_d0,
        array8_address0,
        array8_ce0,
        array8_we0,
        array8_d0,
        array9_address0,
        array9_ce0,
        array9_we0,
        array9_d0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state23 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] array_r_address0;
output   array_r_ce0;
output   array_r_we0;
output  [31:0] array_r_d0;
output  [10:0] array1_address0;
output   array1_ce0;
output   array1_we0;
output  [31:0] array1_d0;
output  [10:0] array2_address0;
output   array2_ce0;
output   array2_we0;
output  [31:0] array2_d0;
output  [10:0] array3_address0;
output   array3_ce0;
output   array3_we0;
output  [31:0] array3_d0;
output  [10:0] array4_address0;
output   array4_ce0;
output   array4_we0;
output  [31:0] array4_d0;
output  [10:0] array5_address0;
output   array5_ce0;
output   array5_we0;
output  [31:0] array5_d0;
output  [10:0] array6_address0;
output   array6_ce0;
output   array6_we0;
output  [31:0] array6_d0;
output  [10:0] array7_address0;
output   array7_ce0;
output   array7_we0;
output  [31:0] array7_d0;
output  [10:0] array8_address0;
output   array8_ce0;
output   array8_we0;
output  [31:0] array8_d0;
output  [10:0] array9_address0;
output   array9_ce0;
output   array9_we0;
output  [31:0] array9_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg array_r_ce0;
reg array_r_we0;
reg array1_ce0;
reg array1_we0;
reg array2_ce0;
reg array2_we0;
reg array3_ce0;
reg array3_we0;
reg array4_ce0;
reg array4_we0;
reg array5_ce0;
reg array5_we0;
reg array6_ce0;
reg array6_we0;
reg array7_ce0;
reg array7_we0;
reg array8_ce0;
reg array8_we0;
reg array9_ce0;
reg array9_we0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [13:0] indvar_flatten17_reg_252;
reg   [4:0] i_reg_263;
reg   [10:0] indvar_flatten_reg_274;
reg   [4:0] ii_reg_285;
reg   [5:0] iii_reg_296;
wire   [13:0] add_ln8_fu_307_p2;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    ap_block_state7_pp0_stage0_iter5;
wire    ap_block_state8_pp0_stage0_iter6;
wire    ap_block_state9_pp0_stage0_iter7;
wire    ap_block_state10_pp0_stage0_iter8;
wire    ap_block_state11_pp0_stage0_iter9;
wire    ap_block_state12_pp0_stage0_iter10;
wire    ap_block_state13_pp0_stage0_iter11;
wire    ap_block_state14_pp0_stage0_iter12;
wire    ap_block_state15_pp0_stage0_iter13;
wire    ap_block_state16_pp0_stage0_iter14;
wire    ap_block_state17_pp0_stage0_iter15;
wire    ap_block_state18_pp0_stage0_iter16;
wire    ap_block_state19_pp0_stage0_iter17;
wire    ap_block_state20_pp0_stage0_iter18;
wire    ap_block_state21_pp0_stage0_iter19;
wire    ap_block_state22_pp0_stage0_iter20;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln8_fu_313_p2;
reg   [0:0] icmp_ln8_reg_524;
reg   [0:0] icmp_ln8_reg_524_pp0_iter1_reg;
reg   [0:0] icmp_ln8_reg_524_pp0_iter2_reg;
reg   [0:0] icmp_ln8_reg_524_pp0_iter3_reg;
reg   [0:0] icmp_ln8_reg_524_pp0_iter4_reg;
reg   [0:0] icmp_ln8_reg_524_pp0_iter5_reg;
wire   [0:0] icmp_ln10_fu_319_p2;
reg   [0:0] icmp_ln10_reg_528;
reg   [0:0] icmp_ln10_reg_528_pp0_iter1_reg;
reg   [0:0] icmp_ln10_reg_528_pp0_iter2_reg;
wire   [4:0] select_ln10_1_fu_331_p3;
reg   [4:0] select_ln10_1_reg_536;
wire   [10:0] select_ln10_6_fu_349_p3;
wire   [4:0] select_ln10_5_fu_435_p3;
reg    ap_enable_reg_pp0_iter3;
wire   [13:0] add_ln14_fu_460_p2;
wire   [5:0] add_ln12_fu_476_p2;
reg   [3:0] trunc_ln_reg_571;
reg   [3:0] trunc_ln_reg_571_pp0_iter7_reg;
reg   [3:0] trunc_ln_reg_571_pp0_iter8_reg;
reg   [3:0] trunc_ln_reg_571_pp0_iter9_reg;
reg   [3:0] trunc_ln_reg_571_pp0_iter10_reg;
reg   [3:0] trunc_ln_reg_571_pp0_iter11_reg;
reg   [3:0] trunc_ln_reg_571_pp0_iter12_reg;
reg   [3:0] trunc_ln_reg_571_pp0_iter13_reg;
reg   [3:0] trunc_ln_reg_571_pp0_iter14_reg;
reg   [3:0] trunc_ln_reg_571_pp0_iter15_reg;
reg   [3:0] trunc_ln_reg_571_pp0_iter16_reg;
reg   [3:0] trunc_ln_reg_571_pp0_iter17_reg;
reg   [3:0] trunc_ln_reg_571_pp0_iter18_reg;
reg   [3:0] trunc_ln_reg_571_pp0_iter19_reg;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter4;
reg    ap_condition_pp0_exit_iter3_state5;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg   [4:0] ap_phi_mux_i_phi_fu_267_p4;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln14_fu_491_p1;
wire   [4:0] add_ln8_1_fu_325_p2;
wire   [10:0] add_ln10_1_fu_343_p2;
wire   [9:0] tmp_2_fu_357_p3;
wire   [0:0] icmp_ln12_fu_384_p2;
wire   [0:0] xor_ln10_fu_379_p2;
wire   [4:0] select_ln10_fu_365_p3;
wire   [0:0] and_ln10_fu_390_p2;
wire   [0:0] or_ln10_fu_402_p2;
wire   [4:0] add_ln10_fu_396_p2;
wire   [9:0] p_mid1_fu_415_p3;
wire   [9:0] select_ln10_2_fu_372_p3;
wire   [9:0] select_ln10_4_fu_423_p3;
wire   [13:0] grp_fu_505_p2;
wire   [7:0] tmp_1_fu_443_p4;
wire   [5:0] select_ln10_3_fu_407_p3;
wire   [13:0] tmp_fu_452_p3;
wire   [13:0] select_ln10_4_cast_fu_431_p1;
wire   [11:0] grp_fu_470_p1;
wire   [28:0] grp_fu_512_p2;
wire   [13:0] grp_fu_470_p2;
wire   [4:0] grp_fu_505_p0;
wire   [10:0] grp_fu_505_p1;
wire   [13:0] grp_fu_512_p0;
wire   [15:0] grp_fu_512_p1;
wire    ap_CS_fsm_state23;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [13:0] grp_fu_505_p00;
wire   [28:0] grp_fu_512_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
end

infer_urem_14ns_12ns_14_18_1 #(
    .ID( 1 ),
    .NUM_STAGE( 18 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 14 ))
urem_14ns_12ns_14_18_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln14_fu_460_p2),
    .din1(grp_fu_470_p1),
    .ce(1'b1),
    .dout(grp_fu_470_p2)
);

infer_mul_mul_5ns_11ns_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 14 ))
mul_mul_5ns_11ns_14_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_505_p0),
    .din1(grp_fu_505_p1),
    .ce(1'b1),
    .dout(grp_fu_505_p2)
);

infer_mul_mul_14ns_16ns_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
mul_mul_14ns_16ns_29_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_512_p0),
    .din1(grp_fu_512_p1),
    .ce(1'b1),
    .dout(grp_fu_512_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter20 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter3_state5)) begin
                ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter2;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln8_reg_524 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_reg_263 <= select_ln10_1_reg_536;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_263 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln8_reg_524_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ii_reg_285 <= select_ln10_5_fu_435_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ii_reg_285 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln8_reg_524_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        iii_reg_296 <= add_ln12_fu_476_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        iii_reg_296 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln8_fu_313_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        indvar_flatten17_reg_252 <= add_ln8_fu_307_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten17_reg_252 <= 14'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln8_fu_313_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        indvar_flatten_reg_274 <= select_ln10_6_fu_349_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_274 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln8_fu_313_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln10_reg_528 <= icmp_ln10_fu_319_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln10_reg_528_pp0_iter1_reg <= icmp_ln10_reg_528;
        icmp_ln8_reg_524 <= icmp_ln8_fu_313_p2;
        icmp_ln8_reg_524_pp0_iter1_reg <= icmp_ln8_reg_524;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln10_reg_528_pp0_iter2_reg <= icmp_ln10_reg_528_pp0_iter1_reg;
        icmp_ln8_reg_524_pp0_iter2_reg <= icmp_ln8_reg_524_pp0_iter1_reg;
        icmp_ln8_reg_524_pp0_iter3_reg <= icmp_ln8_reg_524_pp0_iter2_reg;
        icmp_ln8_reg_524_pp0_iter4_reg <= icmp_ln8_reg_524_pp0_iter3_reg;
        icmp_ln8_reg_524_pp0_iter5_reg <= icmp_ln8_reg_524_pp0_iter4_reg;
        trunc_ln_reg_571_pp0_iter10_reg <= trunc_ln_reg_571_pp0_iter9_reg;
        trunc_ln_reg_571_pp0_iter11_reg <= trunc_ln_reg_571_pp0_iter10_reg;
        trunc_ln_reg_571_pp0_iter12_reg <= trunc_ln_reg_571_pp0_iter11_reg;
        trunc_ln_reg_571_pp0_iter13_reg <= trunc_ln_reg_571_pp0_iter12_reg;
        trunc_ln_reg_571_pp0_iter14_reg <= trunc_ln_reg_571_pp0_iter13_reg;
        trunc_ln_reg_571_pp0_iter15_reg <= trunc_ln_reg_571_pp0_iter14_reg;
        trunc_ln_reg_571_pp0_iter16_reg <= trunc_ln_reg_571_pp0_iter15_reg;
        trunc_ln_reg_571_pp0_iter17_reg <= trunc_ln_reg_571_pp0_iter16_reg;
        trunc_ln_reg_571_pp0_iter18_reg <= trunc_ln_reg_571_pp0_iter17_reg;
        trunc_ln_reg_571_pp0_iter19_reg <= trunc_ln_reg_571_pp0_iter18_reg;
        trunc_ln_reg_571_pp0_iter7_reg <= trunc_ln_reg_571;
        trunc_ln_reg_571_pp0_iter8_reg <= trunc_ln_reg_571_pp0_iter7_reg;
        trunc_ln_reg_571_pp0_iter9_reg <= trunc_ln_reg_571_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln8_fu_313_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        select_ln10_1_reg_536 <= select_ln10_1_fu_331_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln8_reg_524_pp0_iter5_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln_reg_571 <= {{grp_fu_512_p2[28:25]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_condition_pp0_exit_iter3_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter3_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln8_fu_313_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln8_reg_524 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_i_phi_fu_267_p4 = select_ln10_1_reg_536;
    end else begin
        ap_phi_mux_i_phi_fu_267_p4 = i_reg_263;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array1_ce0 = 1'b1;
    end else begin
        array1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (trunc_ln_reg_571_pp0_iter19_reg == 4'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array1_we0 = 1'b1;
    end else begin
        array1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array2_ce0 = 1'b1;
    end else begin
        array2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (trunc_ln_reg_571_pp0_iter19_reg == 4'd2) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array2_we0 = 1'b1;
    end else begin
        array2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array3_ce0 = 1'b1;
    end else begin
        array3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (trunc_ln_reg_571_pp0_iter19_reg == 4'd3) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array3_we0 = 1'b1;
    end else begin
        array3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array4_ce0 = 1'b1;
    end else begin
        array4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (trunc_ln_reg_571_pp0_iter19_reg == 4'd4) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array4_we0 = 1'b1;
    end else begin
        array4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array5_ce0 = 1'b1;
    end else begin
        array5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (trunc_ln_reg_571_pp0_iter19_reg == 4'd5) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array5_we0 = 1'b1;
    end else begin
        array5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array6_ce0 = 1'b1;
    end else begin
        array6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (trunc_ln_reg_571_pp0_iter19_reg == 4'd6) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array6_we0 = 1'b1;
    end else begin
        array6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array7_ce0 = 1'b1;
    end else begin
        array7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (trunc_ln_reg_571_pp0_iter19_reg == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array7_we0 = 1'b1;
    end else begin
        array7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array8_ce0 = 1'b1;
    end else begin
        array8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (trunc_ln_reg_571_pp0_iter19_reg == 4'd8) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array8_we0 = 1'b1;
    end else begin
        array8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array9_ce0 = 1'b1;
    end else begin
        array9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & ((trunc_ln_reg_571_pp0_iter19_reg == 4'd9) | ((trunc_ln_reg_571_pp0_iter19_reg == 4'd10) | ((trunc_ln_reg_571_pp0_iter19_reg == 4'd11) | ((trunc_ln_reg_571_pp0_iter19_reg == 4'd12) | ((trunc_ln_reg_571_pp0_iter19_reg == 4'd13) | ((trunc_ln_reg_571_pp0_iter19_reg == 4'd14) | (trunc_ln_reg_571_pp0_iter19_reg == 4'd15))))))))) begin
        array9_we0 = 1'b1;
    end else begin
        array9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array_r_ce0 = 1'b1;
    end else begin
        array_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (trunc_ln_reg_571_pp0_iter19_reg == 4'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        array_r_we0 = 1'b1;
    end else begin
        array_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter20 == 1'b1) & (ap_enable_reg_pp0_iter19 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter20 == 1'b1) & (ap_enable_reg_pp0_iter19 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_1_fu_343_p2 = (indvar_flatten_reg_274 + 11'd1);

assign add_ln10_fu_396_p2 = (select_ln10_fu_365_p3 + 5'd1);

assign add_ln12_fu_476_p2 = (select_ln10_3_fu_407_p3 + 6'd1);

assign add_ln14_fu_460_p2 = (tmp_fu_452_p3 + select_ln10_4_cast_fu_431_p1);

assign add_ln8_1_fu_325_p2 = (ap_phi_mux_i_phi_fu_267_p4 + 5'd1);

assign add_ln8_fu_307_p2 = (indvar_flatten17_reg_252 + 14'd1);

assign and_ln10_fu_390_p2 = (xor_ln10_fu_379_p2 & icmp_ln12_fu_384_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign array1_address0 = zext_ln14_fu_491_p1;

assign array1_d0 = 32'd0;

assign array2_address0 = zext_ln14_fu_491_p1;

assign array2_d0 = 32'd0;

assign array3_address0 = zext_ln14_fu_491_p1;

assign array3_d0 = 32'd0;

assign array4_address0 = zext_ln14_fu_491_p1;

assign array4_d0 = 32'd0;

assign array5_address0 = zext_ln14_fu_491_p1;

assign array5_d0 = 32'd0;

assign array6_address0 = zext_ln14_fu_491_p1;

assign array6_d0 = 32'd0;

assign array7_address0 = zext_ln14_fu_491_p1;

assign array7_d0 = 32'd0;

assign array8_address0 = zext_ln14_fu_491_p1;

assign array8_d0 = 32'd0;

assign array9_address0 = zext_ln14_fu_491_p1;

assign array9_d0 = 32'd0;

assign array_r_address0 = zext_ln14_fu_491_p1;

assign array_r_d0 = 32'd0;

assign grp_fu_470_p1 = 14'd1549;

assign grp_fu_505_p0 = grp_fu_505_p00;

assign grp_fu_505_p00 = select_ln10_1_fu_331_p3;

assign grp_fu_505_p1 = 14'd704;

assign grp_fu_512_p0 = grp_fu_512_p00;

assign grp_fu_512_p00 = add_ln14_fu_460_p2;

assign grp_fu_512_p1 = 29'd21662;

assign icmp_ln10_fu_319_p2 = ((indvar_flatten_reg_274 == 11'd704) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_384_p2 = ((iii_reg_296 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln8_fu_313_p2 = ((indvar_flatten17_reg_252 == 14'd15488) ? 1'b1 : 1'b0);

assign or_ln10_fu_402_p2 = (icmp_ln10_reg_528_pp0_iter2_reg | and_ln10_fu_390_p2);

assign p_mid1_fu_415_p3 = {{add_ln10_fu_396_p2}, {5'd0}};

assign select_ln10_1_fu_331_p3 = ((icmp_ln10_fu_319_p2[0:0] == 1'b1) ? add_ln8_1_fu_325_p2 : ap_phi_mux_i_phi_fu_267_p4);

assign select_ln10_2_fu_372_p3 = ((icmp_ln10_reg_528_pp0_iter2_reg[0:0] == 1'b1) ? 10'd0 : tmp_2_fu_357_p3);

assign select_ln10_3_fu_407_p3 = ((or_ln10_fu_402_p2[0:0] == 1'b1) ? 6'd0 : iii_reg_296);

assign select_ln10_4_cast_fu_431_p1 = select_ln10_4_fu_423_p3;

assign select_ln10_4_fu_423_p3 = ((and_ln10_fu_390_p2[0:0] == 1'b1) ? p_mid1_fu_415_p3 : select_ln10_2_fu_372_p3);

assign select_ln10_5_fu_435_p3 = ((and_ln10_fu_390_p2[0:0] == 1'b1) ? add_ln10_fu_396_p2 : select_ln10_fu_365_p3);

assign select_ln10_6_fu_349_p3 = ((icmp_ln10_fu_319_p2[0:0] == 1'b1) ? 11'd1 : add_ln10_1_fu_343_p2);

assign select_ln10_fu_365_p3 = ((icmp_ln10_reg_528_pp0_iter2_reg[0:0] == 1'b1) ? 5'd0 : ii_reg_285);

assign tmp_1_fu_443_p4 = {{grp_fu_505_p2[13:6]}};

assign tmp_2_fu_357_p3 = {{ii_reg_285}, {5'd0}};

assign tmp_fu_452_p3 = {{tmp_1_fu_443_p4}, {select_ln10_3_fu_407_p3}};

assign xor_ln10_fu_379_p2 = (icmp_ln10_reg_528_pp0_iter2_reg ^ 1'd1);

assign zext_ln14_fu_491_p1 = grp_fu_470_p2;

endmodule //infer_set3DFloatArray_2
